-- MySQL Script generated by MySQL Workbench
-- Wed Apr 11 11:00:09 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema workshop2
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema workshop2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `workshop2` DEFAULT CHARACTER SET utf8 ;
USE `workshop2` ;

-- -----------------------------------------------------
-- Table `workshop2`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `workshop2`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `role` INT NOT NULL DEFAULT 0,
  `created_at` DATETIME NOT NULL DEFAULT NOW(),
  `updated_at` DATETIME NOT NULL DEFAULT NOW(),
  `active` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `workshop2`.`projects`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `workshop2`.`projects` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `description` TEXT NULL,
  `active` TINYINT NOT NULL DEFAULT 0,
  `created_at` DATETIME NOT NULL DEFAULT NOW(),
  `updated_at` DATETIME NOT NULL DEFAULT NOW(),
  `created_by_id` INT NOT NULL,
  `begin_at` DATETIME NULL DEFAULT NOW(),
  `end_at` DATETIME NULL DEFAULT NOW(),
  PRIMARY KEY (`id`),
  INDEX `fk_projects_users1_idx` (`created_by_id` ASC),
  CONSTRAINT `fk_projects_users1`
    FOREIGN KEY (`created_by_id`)
    REFERENCES `workshop2`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `workshop2`.`team_details`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `workshop2`.`team_details` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `active` TINYINT NOT NULL DEFAULT 0,
  `created_at` DATETIME NOT NULL DEFAULT NOW(),
  `updated_at` DATETIME NOT NULL DEFAULT NOW(),
  `tokens_credit` INT NOT NULL DEFAULT 10,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `workshop2`.`users_team`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `workshop2`.`users_team` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `student_id` INT NOT NULL,
  `active` TINYINT NOT NULL DEFAULT 0,
  `created_at` DATETIME NOT NULL DEFAULT NOW(),
  `updated_at` DATETIME NOT NULL DEFAULT NOW(),
  `team_detail_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_student_team_user_idx` (`student_id` ASC),
  INDEX `fk_projects_team_team_detail1_idx` (`team_detail_id` ASC),
  CONSTRAINT `fk_student_team_user`
    FOREIGN KEY (`student_id`)
    REFERENCES `workshop2`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_projects_team_team_detail1`
    FOREIGN KEY (`team_detail_id`)
    REFERENCES `workshop2`.`team_details` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `workshop2`.`subjects`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `workshop2`.`subjects` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `project_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `description` TEXT NULL,
  `active` TINYINT NOT NULL DEFAULT 0,
  `created_at` DATETIME NOT NULL DEFAULT NOW(),
  `updated_at` DATETIME NULL DEFAULT NOW(),
  `created_by_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_subject_project1_idx` (`project_id` ASC),
  INDEX `fk_subjects_users1_idx` (`created_by_id` ASC),
  CONSTRAINT `fk_subject_project1`
    FOREIGN KEY (`project_id`)
    REFERENCES `workshop2`.`projects` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_subjects_users1`
    FOREIGN KEY (`created_by_id`)
    REFERENCES `workshop2`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `workshop2`.`subjects_team`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `workshop2`.`subjects_team` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `subject_id` INT NOT NULL,
  `team_detail_id` INT NOT NULL,
  `active` TINYINT NOT NULL DEFAULT 0,
  `created_at` DATETIME NULL DEFAULT NOW(),
  `updated_at` DATETIME NULL DEFAULT NOW(),
  PRIMARY KEY (`id`),
  INDEX `fk_team_projects_subject1_idx` (`subject_id` ASC),
  INDEX `fk_team_projects_team_detail1_idx` (`team_detail_id` ASC),
  CONSTRAINT `fk_team_projects_subject1`
    FOREIGN KEY (`subject_id`)
    REFERENCES `workshop2`.`subjects` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_team_projects_team_detail1`
    FOREIGN KEY (`team_detail_id`)
    REFERENCES `workshop2`.`team_details` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `workshop2`.`subjects_coach`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `workshop2`.`subjects_coach` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `coach_id` INT NOT NULL,
  `subjects_id` INT NOT NULL,
  `active` TINYINT NOT NULL DEFAULT 0,
  `created_at` DATETIME NULL DEFAULT NOW(),
  `updated_at` DATETIME NULL DEFAULT NOW(),
  PRIMARY KEY (`id`),
  INDEX `fk_subjects_coach_users1_idx` (`coach_id` ASC),
  INDEX `fk_subjects_coach_subjects1_idx` (`subjects_id` ASC),
  CONSTRAINT `fk_subjects_coach_users1`
    FOREIGN KEY (`coach_id`)
    REFERENCES `workshop2`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_subjects_coach_subjects1`
    FOREIGN KEY (`subjects_id`)
    REFERENCES `workshop2`.`subjects` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `workshop2`.`tokens_transaction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `workshop2`.`tokens_transaction` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `subjects_id` INT NOT NULL,
  `coach_id` INT NOT NULL,
  `team_id` INT NOT NULL,
  `howmany` INT NOT NULL DEFAULT 0,
  `created_at` DATETIME NULL DEFAULT NOW(),
  `updated_at` DATETIME NULL DEFAULT NOW(),
  `active` TINYINT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `fk_tokens_transaction_subjects1_idx` (`subjects_id` ASC),
  INDEX `fk_tokens_transaction_users1_idx` (`coach_id` ASC),
  INDEX `fk_tokens_transaction_team_details1_idx` (`team_id` ASC),
  CONSTRAINT `fk_tokens_transaction_subjects1`
    FOREIGN KEY (`subjects_id`)
    REFERENCES `workshop2`.`subjects` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tokens_transaction_users1`
    FOREIGN KEY (`coach_id`)
    REFERENCES `workshop2`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tokens_transaction_team_details1`
    FOREIGN KEY (`team_id`)
    REFERENCES `workshop2`.`team_details` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
