<?php

namespace ApiBundle\Repository;

/**
 * Subjects_coatchRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Subjects_coatchRepository extends \Doctrine\ORM\EntityRepository
{
}
