<?php

namespace ApiBundle\Repository;

/**
 * SubjectsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubjectsRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param $name
     * @param $project_id
     * @return array
     */
    public function getSubjectByNameAndProjectId($name, $project_id) {
        $subject = $this->createQueryBuilder('u')
            ->where('u.SubjectProject = :project_id AND u.name = :name')
            ->setParameter('project_id', $project_id)
            ->setParameter('name', $name)
            ->getQuery()
            ->getArrayResult();

        return $subject;
    }

    /**
     * @param $project_id
     * @return array
     */
    public function getSubjectByProject($project_id) {

        $subject = $this->createQueryBuilder('u')
            ->where('u.SubjectProject = :project_id AND u.active = :active')
            ->setParameter('project_id', $project_id)
            ->setParameter('active', 1)
            ->getQuery()
            ->getArrayResult();

        return $subject;
    }

    /**
     * @param $team_id
     * @return array
     */
    public function getSubjectByTeam($team_id) {

        $subject = $this->createQueryBuilder('u')
            ->join('u.SubjectTeamDetails', 't', 'WITH', 't.active = :active')
            ->where('t.SubjectTeam = :team_id AND u.active = :active')
            ->setParameter('team_id', $team_id)
            ->setParameter('active', 1)
            ->getQuery()
            ->getArrayResult();

        return $subject;
    }

    /**
     * @param $subject_id
     * @return array
     */
    public function getSubject($subject_id) {
        $subject = $this->createQueryBuilder('u')
            ->where('u.id = :subject_id  AND u.active = :active')
            ->setParameter('subject_id', $subject_id)
            ->setParameter('active', 1)
            ->getQuery()
            ->getArrayResult();

        return $subject;
    }
}
