<?php

namespace ApiBundle\Repository;

/**
 * Subjects_teamRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Subjects_teamRepository extends \Doctrine\ORM\EntityRepository
{
}
