<?php

namespace ApiBundle\Repository;

/**
 * Team_detailsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Team_detailsRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @return array
     */
    public function getTeams()
    {
        $teams = $this->createQueryBuilder('u')
            ->where('u.active = :active')
            ->setParameter('active', 1)
            ->getQuery()
            ->getArrayResult();

        return $teams;
    }

    /**
     * @param $user_id
     * @return array
     */
    public function getTeamByUser($user_id)
    {
        $user = $this->createQueryBuilder('u')
            ->join('u.TeamUsersDetails', 't', 'WITH', 't.active = :active')
            ->where('u.active = :active AND t.TeamUsers = :id')
            ->setParameter('id', $user_id)
            ->setParameter('active', 1)
            ->getQuery()
            ->getArrayResult();

        return $user;
    }

    /**
     * @param $team_id
     * @return array
     */
    public function getTeam($team_id)
    {
        $team = $this->createQueryBuilder('u')
            ->where('u.active = :active AND u.id = :id')
            ->setParameter('id', $team_id)
            ->setParameter('active', 1)
            ->getQuery()
            ->getArrayResult();

        return $team;
    }
}
