<?php

namespace ApiBundle\Repository;

/**
 * Tokens_transactionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Tokens_transactionRepository extends \Doctrine\ORM\EntityRepository
{
}
